// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsyJTjJ47h_ThpLEk57rl8XhCFoIu5RHk',
    appId: '1:276947345340:web:91794015880749804d55b9',
    messagingSenderId: '276947345340',
    projectId: 'firstfire-6d709',
    authDomain: 'firstfire-6d709.firebaseapp.com',
    storageBucket: 'firstfire-6d709.appspot.com',
    measurementId: 'G-2L4D80QVCZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0rJabPCIFG7s2jXtn3LkbBDgi02fhT3c',
    appId: '1:276947345340:android:401f1e756c54d6a34d55b9',
    messagingSenderId: '276947345340',
    projectId: 'firstfire-6d709',
    storageBucket: 'firstfire-6d709.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXQsSOEMm7TZcncnLYhu2l7wArEt3t4cY',
    appId: '1:276947345340:ios:8ee00f7b4c8702204d55b9',
    messagingSenderId: '276947345340',
    projectId: 'firstfire-6d709',
    storageBucket: 'firstfire-6d709.appspot.com',
    iosBundleId: 'com.example.notesapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXQsSOEMm7TZcncnLYhu2l7wArEt3t4cY',
    appId: '1:276947345340:ios:8ee00f7b4c8702204d55b9',
    messagingSenderId: '276947345340',
    projectId: 'firstfire-6d709',
    storageBucket: 'firstfire-6d709.appspot.com',
    iosBundleId: 'com.example.notesapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsyJTjJ47h_ThpLEk57rl8XhCFoIu5RHk',
    appId: '1:276947345340:web:459834ce2e5063774d55b9',
    messagingSenderId: '276947345340',
    projectId: 'firstfire-6d709',
    authDomain: 'firstfire-6d709.firebaseapp.com',
    storageBucket: 'firstfire-6d709.appspot.com',
    measurementId: 'G-XM336JP43X',
  );
}
